name: Enable IRSA
description: Enable IAM Roles for Service Accounts
check_id: IRSA Implementation
remediation_type: cloudformation
template:
  AWSTemplateFormatVersion: '2010-09-09'
  Resources:
    EKSOIDCProvider:
      Type: AWS::IAM::OIDCProvider
      Properties:
        Url: '{{cluster.oidc_issuer_url}}'
        ClientIdList: ['sts.amazonaws.com']
        ThumbprintList: ['9e99a48a9960b14926bb7f3b02e22da2b0ab7280']
  Outputs:
    OIDCProviderARN:
      Value:
        Fn::GetAtt: ['EKSOIDCProvider', 'Arn']